version: 1.0.{build}
image: Visual Studio 2019

build_script:
  - npm install
  - npm run build

deploy:
  provider: GitHubPages
  repository: Elizabess/widget
  branch: gh-pages
  folder: dist
  on:
    branch: main
  token: %GITHUB_TOKEN%
